name: Fetch

on:
  workflow_dispatch:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

        
    - name: Download
      run: |
       ls /usr/bin/google-chrome
       pip3 install -r requirements.txt
       python3 crawl.py ${{ github.ref }} headless
       tree
    - name: Set env
      run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV

    - name: Upload artifacts
      uses: svenstaro/upload-release-action@v2
      with:
        repo_token: ${{ secrets.GITHUB_TOKEN }}
        file: ./downloads/*
        tag: ${{ github.ref }}
        file_glob: true
        overwrite: true

